# -*- coding: utf-8 -*-
"""score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tWn1antM_G0kLdFLTXjbECsZbvrQ7Mtq
"""

Student=int(input())
Apple=int(input())
print(Apple//Student)
print(Apple%Student)

data=input()
start=int(input())
stop=int(input())
print(data[start:stop+1:1])

StrA=input()
StrB=input()

print(StrB in StrA)

celsius = float(input())
fahrenheit = (celsius * 9/5) + 32
print(f"{fahrenheit:.1f} ")

main_string = input("請輸入字串: ")
substring = input("請輸入子字串: ")
index = main_string.find(substring)
if index != -1:
    print(f"子字串 '{substring}' 在字串中第一次出現的索引位置是: {index}")
else:
    print("-1 (找不到子字串)")

phone=str1[0:10:1]
phone1=str1[0:4]

main_str = input().strip()
sub_str = input().strip()
print(find(main_str, sub_str))

main_string = int(input("請輸入字串: "))
substring = int(input("請輸入子字串: "))
index = str.find(main_string,beg=0,end=len(main_string))

first_name = input().strip()
last_name = input().strip()
print("Replace result:", last_name, first_name)

num= input()
integer_part = int(num.split('.')[0])
unit_digit = integer_part % 10
decimal_part = num.split('.')[1][0]
print(unit_digit)
print(decimal_part)

str1 = input()
phone = str1[0:10]
phone1 = phone[0:4]
phone2 = phone[4:7]
phone3 = phone[7:10]
formatted_phone = phone1 + '-' + phone2 + '-' + phone3
name = str1[10:]
name_length = len(name)
masked_name = name[0] + 'O' + name[-1]
print(f"{name}的手機號碼是{formatted_phone}")
print(f"{name}的名字有{name_length}個字元")
print(f"{name}因應個資法隱藏中間一個字之後變成{masked_name}")

input_str = input("請輸入一串以空格分隔的字串：")
words = input_str.split()
words.sort()
print(words)

name1 = input("請輸入第一組姓名 (格式: First Name Last Name)：")
name2 = input("請輸入第二組姓名 (格式: First Name Last Name)：")
first_name1, last_name1 = name1.split()
first_name2, last_name2 = name2.split()
print(f"{first_name1} {last_name2}")
print(f"{first_name2} {last_name1}")

score=input().split()
countF=0
for i in score:
  if int(i)<60:
    countF += 1
    print('不及格人數:'countF)